LABEL_TEXT = {
    "likely_ai": (
        "Our system thinks this was likely generated by AI. This isn't a certainty — "
        "it's based on writing patterns our tools detected, and we could be wrong. "
        "If this is your original work, you can appeal this result and a person will review it."
    ),
    "uncertain": (
        "We're not confident enough to say whether this was written by a person or by AI. "
        "This label just means our tools picked up a mix of signals — it's not a judgment "
        "on your work. No action is needed unless you want to appeal for a closer look."
    ),
    "likely_human": (
        "Our system did not detect signs of AI generation in this piece — it reads as "
        "human-written. As with any automated check, this isn't a guarantee, just our best read."
    ),
}


def get_label_text(attribution):
    """Return the verbatim transparency label text for a given attribution."""
    return LABEL_TEXT[attribution]


if __name__ == "__main__":
    from confidence import compute_confidence, attribute
    from signals import classify_with_llm
    from stylometry import compute_stylo_score

    test_inputs = [
        (
            "clearly_ai",
            "Artificial intelligence represents a transformative paradigm shift in modern society. "
            "It is important to note that while the benefits of AI are numerous, it is equally "
            "essential to consider the ethical implications. Furthermore, stakeholders across "
            "various sectors must collaborate to ensure responsible deployment.",
        ),
        (
            "clearly_human",
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after. my friend got the spicy version and "
            "said it was better. probably won't go back unless someone drags me there",
        ),
        (
            "borderline_formal_human",
            "The relationship between monetary policy and asset price inflation has been "
            "extensively studied in the literature. Central banks face a fundamental tension "
            "between their mandate for price stability and the unintended consequences of "
            "prolonged low interest rates on equity and real estate valuations.",
        ),
    ]

    seen_attributions = set()
    for name, text in test_inputs:
        llm_result = classify_with_llm(text)
        stylo_result = compute_stylo_score(text)
        confidence = compute_confidence(llm_result, stylo_result["stylo_score"])
        attribution = attribute(confidence["combined_score"])
        label_text = get_label_text(attribution)
        seen_attributions.add(attribution)

        print(f"--- {name} ---")
        print(f"combined_score: {confidence['combined_score']} -> attribution: {attribution}")
        print(f"label: {label_text}")
        print()

    print(f"Attributions reached: {seen_attributions}")
    print(f"All 3 variants reachable: {seen_attributions == {'likely_ai', 'uncertain', 'likely_human'}}")
