import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client


SYSTEM_PROMPT = """You are a text-provenance classifier. Your job is to judge whether a piece of writing was likely written by a human or generated by an AI language model.

Judge based on voice, idea flow, topical coherence, and overall "feel" — not just surface grammar. AI-generated text often reads as evenly hedged, thesis-driven, and low on genuine surprise. Human writing tends to have more idiosyncrasy, tangents, and uneven pacing.

Examples:

Text: "honestly idk why but i always end up rewatching the same three episodes when im stressed. its not even that theyre good episodes lol. i think its just familiar"
Assessment: {"llm_ai_probability": 0.05, "label": "likely_human", "reason": "Casual, inconsistent capitalization, meandering self-aware tangent typical of unedited human writing."}

Text: "In today's fast-paced world, effective time management has become more important than ever. By prioritizing tasks and setting clear goals, individuals can significantly improve their productivity and achieve a healthier work-life balance."
Assessment: {"llm_ai_probability": 0.9, "label": "likely_ai", "reason": "Generic thesis-driven opener, evenly hedged claims, smooth transitions with no specific detail or voice."}

Text: "My grandmother's kitchen always smelled like burnt garlic and cardamom, a combination I've never been able to recreate no matter how many times I've tried her recipe from memory."
Assessment: {"llm_ai_probability": 0.1, "label": "likely_human", "reason": "Specific sensory detail and a personal, slightly rueful admission of failure — hard-to-fabricate specificity."}

Text: "It is important to note that there are several factors to consider when evaluating this topic. On one hand, there are clear benefits. On the other hand, potential drawbacks must also be acknowledged."
Assessment: {"llm_ai_probability": 0.85, "label": "likely_ai", "reason": "Formulaic hedge-both-sides structure, vague throughout, no concrete claims or examples."}

For the given text, respond with ONLY a JSON object in this exact shape, no other commentary:
{"llm_ai_probability": <float 0.0-1.0>, "label": "likely_human"|"likely_ai"|"uncertain", "reason": "<short rationale>"}
"""


def classify_with_llm(text):
    """Send text to Groq for AI/human classification.

    Returns a dict: {llm_ai_probability, label, reason, status}
    status is one of: success, parse_failure, schema_violation, injection_flagged
    """
    try:
        response = _get_client().chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Text:\n{text}\n\nAssessment:"},
            ],
            temperature=0.2,
            response_format={"type": "json_object"},
        )
    except Exception as e:
        return {
            "llm_ai_probability": None,
            "label": "uncertain",
            "reason": f"Groq API call failed: {e}",
            "status": "parse_failure",
        }

    raw_content = response.choices[0].message.content

    try:
        parsed = json.loads(raw_content)
    except (json.JSONDecodeError, TypeError):
        return {
            "llm_ai_probability": None,
            "label": "uncertain",
            "reason": "Model response was not valid JSON.",
            "status": "parse_failure",
        }

    probability = parsed.get("llm_ai_probability")
    label = parsed.get("label")
    reason = parsed.get("reason", "")

    if (
        not isinstance(probability, (int, float))
        or not (0.0 <= probability <= 1.0)
        or label not in ("likely_human", "likely_ai", "uncertain")
    ):
        return {
            "llm_ai_probability": None,
            "label": "uncertain",
            "reason": "Model response violated the expected schema.",
            "status": "schema_violation",
        }

    return {
        "llm_ai_probability": float(probability),
        "label": label,
        "reason": reason,
        "status": "success",
    }


if __name__ == "__main__":
    test_inputs = [
        "In today's fast-paced world, effective communication has become more important than ever. By fostering open dialogue and embracing diverse perspectives, organizations can significantly enhance collaboration and drive meaningful innovation.",
        "ugh i spilled coffee all over my laptop this morning and now the space bar sticks. great start to the day lol",
        "The sun dipped below the horizon, painting the sky in hues of amber and rose. I sat on the porch, coffee in hand, watching the neighborhood slowly go quiet.",
        "Furthermore, it is essential to consider the multifaceted implications of this decision. On one hand, there are numerous advantages; on the other hand, certain challenges must not be overlooked.",
    ]

    for i, text in enumerate(test_inputs, 1):
        result = classify_with_llm(text)
        print(f"--- Test {i} ---")
        print(f"Text: {text[:80]}...")
        print(json.dumps(result, indent=2))
        print()
